# Generated by Django 2.1.7 on 2019-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stage',
            field=models.CharField(choices=[('PhD', 'PhD'), ('Msc', "Master's degree"), ('Und', 'Undergraduate degree')], default='Und', max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
