# Generated by Django 2.1.7 on 2019-06-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190603_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year')], max_length=1),
        ),
    ]
