# Generated by Django 2.1.7 on 2019-06-04 21:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190603_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Maths', 'Maths')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(upload_to=accounts.models.user_directory_path),
        ),
    ]
