# Generated by Django 2.1.7 on 2019-06-07 17:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190605_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the course', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, help_text='Type down and/or select your course from the list', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(help_text='Upload your CV', upload_to=accounts.models.user_directory_path),
        ),
    ]
