# Generated by Django 2.2.2 on 2019-06-20 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190620_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='applicants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
