# Generated by Django 2.2.2 on 2019-06-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190620_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
