# Generated by Django 2.1.7 on 2019-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aggregate_consent',
            field=models.BooleanField(default=False, help_text='Tick if you consent to having your information be aggregated and disclosed completely anonymously with sponsors for the purposes of improving the society'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], default='N', help_text='Select your gender', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.IntegerField(choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year')], default=1),
        ),
    ]
