# Generated by Django 2.1.7 on 2019-09-23 18:44

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190920_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aggregate_consent',
            field=models.BooleanField(default=False, help_text='Tick if you consent to having your information be aggregated and disclosed completely anonymously with sponsors for the purposes of improving the society.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(help_text='Upload your CV. Please do not upload any information that is confidential to you and you would not want to share with a recruiter.', upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
