# Generated by Django 2.1.7 on 2019-10-10 09:04

import accounts.models
import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190923_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(help_text='Upload your CV. Please do not upload any information that is confidential to you and you would not want to share with a recruiter.', upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), accounts.validators.validate_file_size]),
        ),
    ]
