# Generated by Django 3.0.5 on 2020-04-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200423_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, help_text='A slug to identify posts by this category', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
