# Generated by Django 3.0.5 on 2020-04-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the matieral', max_length=100)),
                ('description', models.TextField(help_text='Description of the material', max_length=1000)),
                ('link', models.CharField(blank=True, help_text='Link of the material', max_length=100)),
                ('attachment', models.FileField(blank=True, help_text='File attached to the material', upload_to='materials/')),
                ('visible', models.BooleanField(help_text='Is the material currently visible?')),
                ('category', models.CharField(choices=[('Workshop', 'Workshop'), ('Featured Works', 'Featured Works'), ('Course', 'Course')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the question', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the proposal', max_length=100)),
                ('description', models.TextField(help_text='Description of the proposal', max_length=1000)),
                ('active', models.BooleanField(help_text='Proposal actively displayed')),
                ('applicants', models.ManyToManyField(blank=True, help_text='Applicants for the proposal', related_name='Applicants', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(help_text='Author of the proposal', on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('subtitle', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('category', models.CharField(choices=[('Partnerships', 'Partnerships'), ('Events', 'Events'), ('Technology', 'Technology'), ('Research', 'Research'), ('Committee', 'Committee')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the opportunity', max_length=100)),
                ('subtitle', models.CharField(help_text='Subtitle of the opportunity', max_length=300)),
                ('description', models.TextField(help_text='Description of the opportunity', max_length=1000)),
                ('image', models.ImageField(blank=True, help_text='Image displayed for the opportunity', upload_to='')),
                ('visible', models.BooleanField(default=False, help_text='Is the opportunity currently visible')),
                ('questions', models.ManyToManyField(blank=True, help_text='Additional questions related to the opportunity', to='hub.Question')),
                ('users', models.ManyToManyField(blank=True, help_text='Users that have applied to this opportunity', to=settings.AUTH_USER_MODEL)),
                ('visible_to', models.ManyToManyField(blank=True, default=None, help_text='Users that can see this opportunity, leave blank for open to all users', related_name='opportunity_visible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'opportunities',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful', models.BooleanField(default=False, help_text='Has the application been successfull, or got an interview?')),
                ('answers', models.ManyToManyField(help_text='Answers', to='hub.Answer')),
                ('opportunity', models.ForeignKey(help_text='Application', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hub.Opportunity')),
                ('user', models.ForeignKey(help_text='Applicant', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer', to='hub.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
