# Generated by Django 2.2.2 on 2019-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20190624_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the matieral', max_length=100)),
                ('description', models.TextField(help_text='Description of the material', max_length=1000)),
                ('link', models.CharField(help_text='Link of the material', max_length=100)),
                ('category', models.CharField(choices=[('Workshop', 'Workshop'), ('Case study', 'Case study'), ('Courses', 'Courses')], max_length=20)),
            ],
        ),
    ]
