# Generated by Django 2.2.2 on 2019-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Case study', 'Case study'), ('Course', 'Course')], max_length=20),
        ),
    ]
