# Generated by Django 2.1.7 on 2019-08-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0006_auto_20190727_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the proposal', max_length=100)),
                ('description', models.TextField(help_text='Description of the proposal', max_length=1000)),
                ('applicants', models.ManyToManyField(blank=True, help_text='Applicants for the proposal', related_name='Applicants', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(help_text='Author of the proposal', on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
