# Generated by Django 2.1.7 on 2019-09-18 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0009_material_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(help_text='Answers', to='hub.Answer')),
                ('opportunity', models.ForeignKey(help_text='Opportunity', on_delete=django.db.models.deletion.CASCADE, related_name='opportunity', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Applicant', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'opportunities'},
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='applicants',
        ),
    ]
