# Generated by Django 2.1.7 on 2019-09-19 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0010_auto_20190918_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users that have applied to this opportunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(help_text='Application', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hub.Opportunity'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(help_text='Applicant', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
