# Generated by Django 2.1.7 on 2019-09-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_auto_20190919_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Featured Works', 'Featured Works'), ('Course', 'Course')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.CharField(blank=True, help_text='Link of the material', max_length=100),
        ),
    ]
