# Generated by Django 2.1.7 on 2019-09-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_auto_20190919_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='name',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='subtitle',
            field=models.CharField(default='Empty', help_text='Subtitle of the opportunity', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='title',
            field=models.CharField(default='Empty', help_text='Title of the opportunity', max_length=100),
            preserve_default=False,
        ),
    ]
