# Generated by Django 2.1.7 on 2019-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_auto_20190923_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(default=0, help_text='Image displayed for the opportunity', upload_to=''),
            preserve_default=False,
        ),
    ]
