# Generated by Django 3.0.5 on 2020-06-20 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0015_auto_20191010_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='successful',
            field=models.BooleanField(default=False, help_text='Has the application been successfull, or got an interview?'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='visible_to',
            field=models.ManyToManyField(blank=True, default=None, help_text='Users that can see this opportunity, leave blank for open to all users', related_name='opportunity_visible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(help_text='Name of the question', max_length=500),
        ),
    ]
